debounced_emails_crawler: fix levelup cleanup
Following the use of levelup own promises, we now need to bind the db object
In absence of that context, the `db.del.bind(null, key)` call was throwing the following error:
`TypeError: db._isOpening is not a function`