fix circular dependency
requesting a non-existing static file, such as
GET /public/i18n/nonexistinglang.json
was making the server crash with 'TypeError: assert_.object is not a function'
instead of returning a nice 404